#配置模板
#https://docs.spring.io/spring-boot/docs/1.4.0.RELEASE/reference/html/common-application-properties.html

zookeeper:
  address: 192.168.136.131:4180
  retry: 1000
msql-hdfs-mirco:
  address: 192.168.136.131
  port: 8080
  name: placeService
  path: gleaning